config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  post '/admin_controler/search_options' => 'admin_controler#search_options' 
  get '/admin_controler/index' => 'admin_controler#index'
  get '/admin_controler/users' => 'admin_controler#users'
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment , length: {minimum: 2}





end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user! 
    before_action :have_access! ,only: [:destroy]



    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create (comment_params)
        @comment.user_id= current_user.id
        if (@comment.save)
            redirect_to @post , notice: "Comment posted successfully"
        else
            redirect_to  post_path(@post) , alert: "Error creating comment, Comment must have minimum 2 charc"
        end 

    end 

    def destroy 
        @comment = Comment.find(params[:id])
        if (@comment.delete)
            redirect_to post_path(@comment.post) , notice: "Comment deleted successfully"
        else 
            redirect_to  post_path(@comment.post) , alert: "Error deleting comment"
        end 

    end 











    private

    def comment_params
        params.require(:comment).permit(:comment)
    end 

    def have_access!
        @comment = Comment.find(params[:id])
        @post= Post.find(params[:post_id])
        unless current_user.admin? || @comment.user_id == current_user.id
            redirect_to @post, alert: "Un Authurized Action"
        end 
    end 

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div>
    <!-- looping comments-->
    <% if @comments.any? %><hr>
        <h4>Comments</h4>
        <% @comments.each do |comment| %>
            <strong><%= "#{comment.user.username} :" %></strong> 
            <%= comment.comment  %>
            <!--checking accessability for deleting comment-->
            <% if current_user %>
                <%= link_to(" [X]" , post_comment_path(comment.post,comment), method: :delete , 
                                    data: {confirm: "Are you sure?"}) if current_user.comment_access?(comment) %>
            <% end %>
            <br>
        <% end %>
    <% end %>
</div>

<hr>
<!--rendering comment form-->
<%= render 'comments/form' , form: ([@post , @post.comments.build]) , path: post_comments_path(@post) ,
                                    method: :post %><br><hr>

app/views/comments/_form.html.erb
<!--form for new comment-->
<%= form_for form , url: path , method: method do |f| %>

    <%= f.label :comment %><br>
    <%= f.text_area( :comment , :class => 'form-control') %><br>

    <%= f.submit(:class => 'btn btn-outline-primary') %>

<% end %>